name: dorm_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.6.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.2.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  curved_navigation_bar: ^1.0.6
  ionicons: ^0.2.2
  counter_button: ^1.0.1
  form_field_validator: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.4
  sembast: ^3.7.3+2
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  flutter_localization: ^0.2.2
  flutter_rating_bar: ^4.0.1
  image_cropper: ^8.0.2
  dotted_border: ^2.1.0
  intl: ^0.19.0
  photo_view: ^0.15.0
  firebase_performance: ^0.10.0+8
  crypto: ^3.0.5
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  mailer: ^6.2.0
  provider: ^6.1.2

flutter_icons:
  android: true
  image_path: "assets/images/logo/Accom.png"


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/dorm/1 (1).jpg
    - assets/images/dorm/back.png
    - assets/images/บ้านแสนสุข/master (1).jpg
    - assets/images/บ้านแสนสุข/Screenshot (453).png
    - assets/images/บ้านแสนสุข/2.jpg
    - assets/images/บ้านแสนสุข/3.jpg
    # - assets\images\บ้านแสนสุข\4.jpg
    # - assets\images\บ้านแสนสุข\5.jpg

